// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AdopcionesDocumentDataSlicesSlice = CatCardSlice | DogCardSlice;

/**
 * Content for adopciones documents
 */
interface AdopcionesDocumentData {
  /**
   * portadaizq field in *adopciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: adopciones.portadaizq
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portadaizq: prismic.ImageField<never>;

  /**
   * portadader field in *adopciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: adopciones.portadader
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portadader: prismic.ImageField<never>;

  /**
   * buscadorperrito field in *adopciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: adopciones.buscadorperrito
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  buscadorperrito: prismic.ImageField<never>;

  /**
   * buscadorgatito field in *adopciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: adopciones.buscadorgatito
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  buscadorgatito: prismic.ImageField<never>;

  /**
   * Slice Zone field in *adopciones*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: adopciones.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AdopcionesDocumentDataSlicesSlice> /**
   * Meta Description field in *adopciones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: adopciones.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *adopciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: adopciones.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *adopciones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: adopciones.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * adopciones document from Prismic
 *
 * - **API ID**: `adopciones`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AdopcionesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AdopcionesDocumentData>,
    "adopciones",
    Lang
  >;

type ContactoDocumentDataSlicesSlice = never;

/**
 * Content for contacto documents
 */
interface ContactoDocumentData {
  /**
   * portada1 field in *contacto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.portada1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada1: prismic.ImageField<never>;

  /**
   * portada2 field in *contacto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.portada2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada2: prismic.ImageField<never>;

  /**
   * portada3 field in *contacto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.portada3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada3: prismic.ImageField<never>;

  /**
   * contactofoto field in *contacto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.contactofoto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  contactofoto: prismic.ImageField<never>;

  /**
   * Slice Zone field in *contacto*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactoDocumentDataSlicesSlice> /**
   * Meta Description field in *contacto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contacto.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *contacto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *contacto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contacto.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * contacto document from Prismic
 *
 * - **API ID**: `contacto`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactoDocumentData>,
    "contacto",
    Lang
  >;

type DonacionesDocumentDataSlicesSlice = never;

/**
 * Content for donaciones documents
 */
interface DonacionesDocumentData {
  /**
   * textportada field in *donaciones*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.textportada
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textportada: prismic.RichTextField;

  /**
   * fondocirculos field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.fondocirculos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fondocirculos: prismic.ImageField<never>;

  /**
   * formvectorgato field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.formvectorgato
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  formvectorgato: prismic.ImageField<never>;

  /**
   * gatoportada field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.gatoportada
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gatoportada: prismic.ImageField<never>;

  /**
   * yapeicono field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.yapeicono
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  yapeicono: prismic.ImageField<never>;

  /**
   * yapeqr field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.yapeqr
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  yapeqr: prismic.ImageField<never>;

  /**
   * logobcp field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.logobcp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logobcp: prismic.ImageField<never>;

  /**
   * donacion1 field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.donacion1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  donacion1: prismic.ImageField<never>;

  /**
   * donacion2 field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.donacion2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  donacion2: prismic.ImageField<never>;

  /**
   * donacion3 field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.donacion3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  donacion3: prismic.ImageField<never>;

  /**
   * donacion4 field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.donacion4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  donacion4: prismic.ImageField<never>;

  /**
   * donacion5 field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.donacion5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  donacion5: prismic.ImageField<never>;

  /**
   * grafica field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.grafica
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  grafica: prismic.ImageField<never>;

  /**
   * Slice Zone field in *donaciones*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DonacionesDocumentDataSlicesSlice> /**
   * Meta Description field in *donaciones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: donaciones.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *donaciones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donaciones.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *donaciones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: donaciones.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * donaciones document from Prismic
 *
 * - **API ID**: `donaciones`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DonacionesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DonacionesDocumentData>,
    "donaciones",
    Lang
  >;

type EventosDocumentDataSlicesSlice = EventoSlice;

/**
 * Content for eventos documents
 */
interface EventosDocumentData {
  /**
   * portada1 field in *eventos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.portada1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada1: prismic.ImageField<never>;

  /**
   * portada2 field in *eventos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.portada2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada2: prismic.ImageField<never>;

  /**
   * portada3 field in *eventos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.portada3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada3: prismic.ImageField<never>;

  /**
   * Slice Zone field in *eventos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventosDocumentDataSlicesSlice> /**
   * Meta Description field in *eventos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: eventos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *eventos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: eventos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *eventos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: eventos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * eventos document from Prismic
 *
 * - **API ID**: `eventos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EventosDocumentData>,
    "eventos",
    Lang
  >;

type FooterDocumentDataSlicesSlice = never;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * logofooter field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logofooter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logofooter: prismic.ImageField<never>;

  /**
   * Slice Zone field in *footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Meta Description field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: footer.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: footer.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type IndexDocumentDataSlicesSlice = never;

/**
 * Content for index documents
 */
interface IndexDocumentData {
  /**
   * portada field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.portada
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada: prismic.ImageField<never>;

  /**
   * formvector field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.formvector
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  formvector: prismic.ImageField<never>;

  /**
   * logoportada field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.logoportada
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logoportada: prismic.ImageField<never>;

  /**
   * cuadro1 field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.cuadro1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cuadro1: prismic.ImageField<never>;

  /**
   * cuadro2 field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.cuadro2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cuadro2: prismic.ImageField<never>;

  /**
   * cuadro3 field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.cuadro3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cuadro3: prismic.ImageField<never>;

  /**
   * cuadro4 field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.cuadro4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cuadro4: prismic.ImageField<never>;

  /**
   * cuadro5 field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.cuadro5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cuadro5: prismic.ImageField<never>;

  /**
   * cuadro6 field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.cuadro6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cuadro6: prismic.ImageField<never>;

  /**
   * imagencomida field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.imagencomida
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagencomida: prismic.ImageField<never>;

  /**
   * imagensalud field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.imagensalud
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagensalud: prismic.ImageField<never>;

  /**
   * Slice Zone field in *index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IndexDocumentDataSlicesSlice> /**
   * Meta Description field in *index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<IndexDocumentData>, "index", Lang>;

type NavbarDocumentDataSlicesSlice = never;

/**
 * Content for navbar documents
 */
interface NavbarDocumentData {
  /**
   * logo field in *navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *navbar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavbarDocumentDataSlicesSlice> /**
   * Meta Description field in *navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: navbar.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: navbar.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

type NosotrosDocumentDataSlicesSlice = never;

/**
 * Content for nosotros documents
 */
interface NosotrosDocumentData {
  /**
   * imagedecorizq field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.imagedecorizq
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagedecorizq: prismic.ImageField<never>;

  /**
   * imagedecorder field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.imagedecorder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagedecorder: prismic.ImageField<never>;

  /**
   * imageorg field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.imageorg
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageorg: prismic.ImageField<never>;

  /**
   * imagehistoriafondo field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.imagehistoriafondo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagehistoriafondo: prismic.ImageField<never>;

  /**
   * imagehistoria1 field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.imagehistoria1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagehistoria1: prismic.ImageField<never>;

  /**
   * imagehistoria2 field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.imagehistoria2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagehistoria2: prismic.ImageField<never>;

  /**
   * videoadra field in *nosotros*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.videoadra
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  videoadra: prismic.LinkToMediaField;

  /**
   * mision1 field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.mision1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mision1: prismic.ImageField<never>;

  /**
   * mision2 field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.mision2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mision2: prismic.ImageField<never>;

  /**
   * mision3 field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.mision3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mision3: prismic.ImageField<never>;

  /**
   * mision4 field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.mision4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mision4: prismic.ImageField<never>;

  /**
   * mision5 field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.mision5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mision5: prismic.ImageField<never>;

  /**
   * Slice Zone field in *nosotros*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NosotrosDocumentDataSlicesSlice> /**
   * Meta Description field in *nosotros*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: nosotros.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *nosotros*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *nosotros*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: nosotros.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * nosotros document from Prismic
 *
 * - **API ID**: `nosotros`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NosotrosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NosotrosDocumentData>,
    "nosotros",
    Lang
  >;

type RescatistasDocumentDataSlicesSlice = never;

type RescatistasDocumentDataSlices2Slice = CardRescatistaSlice;

type RescatistasDocumentDataSlices3Slice = CasosRescateSlice;

type RescatistasDocumentDataSlices4Slice = FotosCasoSlice;

/**
 * Content for rescatistas documents
 */
interface RescatistasDocumentData {
  /**
   * portada1 field in *rescatistas*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rescatistas.portada1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada1: prismic.ImageField<never>;

  /**
   * portada2 field in *rescatistas*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rescatistas.portada2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada2: prismic.ImageField<never>;

  /**
   * portada3 field in *rescatistas*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rescatistas.portada3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portada3: prismic.ImageField<never>;

  /**
   * Slice Zone field in *rescatistas*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rescatistas.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RescatistasDocumentDataSlicesSlice> /**
   * Meta Description field in *rescatistas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: rescatistas.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *rescatistas*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rescatistas.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *rescatistas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: rescatistas.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Slice Zone field in *rescatistas*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rescatistas.slices2[]
   * - **Tab**: CardRescatista
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<RescatistasDocumentDataSlices2Slice> /**
   * Slice Zone field in *rescatistas*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rescatistas.slices3[]
   * - **Tab**: CasosRescatista
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<RescatistasDocumentDataSlices3Slice> /**
   * Slice Zone field in *rescatistas*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: rescatistas.slices4[]
   * - **Tab**: FotosCaso
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices4: prismic.SliceZone<RescatistasDocumentDataSlices4Slice>;
}

/**
 * rescatistas document from Prismic
 *
 * - **API ID**: `rescatistas`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RescatistasDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RescatistasDocumentData>,
    "rescatistas",
    Lang
  >;

export type AllDocumentTypes =
  | AdopcionesDocument
  | ContactoDocument
  | DonacionesDocument
  | EventosDocument
  | FooterDocument
  | IndexDocument
  | NavbarDocument
  | NosotrosDocument
  | RescatistasDocument;

/**
 * Primary content in *CardRescatista → Primary*
 */
export interface CardRescatistaSliceDefaultPrimary {
  /**
   * fotoprofile field in *CardRescatista → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_rescatista.primary.fotoprofile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fotoprofile: prismic.ImageField<never>;

  /**
   * nombre field in *CardRescatista → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_rescatista.primary.nombre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;

  /**
   * celular field in *CardRescatista → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_rescatista.primary.celular
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  celular: prismic.KeyTextField;

  /**
   * cuentabancaria field in *CardRescatista → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_rescatista.primary.cuentabancaria
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cuentabancaria: prismic.RichTextField;

  /**
   * descripcion field in *CardRescatista → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_rescatista.primary.descripcion
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descripcion: prismic.RichTextField;

  /**
   * yapeqr field in *CardRescatista → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_rescatista.primary.yapeqr
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  yapeqr: prismic.ImageField<never>;

  /**
   * uid field in *CardRescatista → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_rescatista.primary.uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;
}

/**
 * Default variation for CardRescatista Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardRescatistaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardRescatistaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardRescatista*
 */
type CardRescatistaSliceVariation = CardRescatistaSliceDefault;

/**
 * CardRescatista Shared Slice
 *
 * - **API ID**: `card_rescatista`
 * - **Description**: CardRescatista
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardRescatistaSlice = prismic.SharedSlice<
  "card_rescatista",
  CardRescatistaSliceVariation
>;

/**
 * Primary content in *CasosRescate → Items*
 */
export interface CasosRescateSliceDefaultItem {
  /**
   * fotoperrito field in *CasosRescate → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: casos_rescate.items[].fotoperrito
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fotoperrito: prismic.ImageField<never>;

  /**
   * nombre field in *CasosRescate → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: casos_rescate.items[].nombre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;

  /**
   * edad field in *CasosRescate → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: casos_rescate.items[].edad
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  edad: prismic.KeyTextField;

  /**
   * historia field in *CasosRescate → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: casos_rescate.items[].historia
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  historia: prismic.RichTextField;

  /**
   * sobremi field in *CasosRescate → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: casos_rescate.items[].sobremi
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sobremi: prismic.RichTextField;

  /**
   * donacionesyapoyo field in *CasosRescate → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: casos_rescate.items[].donacionesyapoyo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  donacionesyapoyo: prismic.RichTextField;

  /**
   * encurso field in *CasosRescate → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: casos_rescate.items[].encurso
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  encurso: prismic.BooleanField;
}

/**
 * Default variation for CasosRescate Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasosRescateSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CasosRescateSliceDefaultItem>
>;

/**
 * Slice variation for *CasosRescate*
 */
type CasosRescateSliceVariation = CasosRescateSliceDefault;

/**
 * CasosRescate Shared Slice
 *
 * - **API ID**: `casos_rescate`
 * - **Description**: CasosRescate
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasosRescateSlice = prismic.SharedSlice<
  "casos_rescate",
  CasosRescateSliceVariation
>;

/**
 * Primary content in *CatCard → Items*
 */
export interface CatCardSliceDefaultItem {
  /**
   * nombre field in *CatCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_card.items[].nombre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;

  /**
   * edad field in *CatCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_card.items[].edad
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  edad: prismic.KeyTextField;

  /**
   * lugar field in *CatCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_card.items[].lugar
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lugar: prismic.KeyTextField;

  /**
   * tamanhio field in *CatCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_card.items[].tamanhio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tamanhio: prismic.KeyTextField;

  /**
   * esterilizacion field in *CatCard → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: cat_card.items[].esterilizacion
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  esterilizacion: prismic.BooleanField;

  /**
   * peso field in *CatCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_card.items[].peso
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  peso: prismic.KeyTextField;

  /**
   * vacunas field in *CatCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_card.items[].vacunas
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  vacunas: prismic.RichTextField;

  /**
   * descripcion field in *CatCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_card.items[].descripcion
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descripcion: prismic.RichTextField;

  /**
   * tipo field in *CatCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: cat
   * - **API ID Path**: cat_card.items[].tipo
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tipo: prismic.SelectField<"cat" | "dog", "filled">;

  /**
   * sexo field in *CatCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Selecciona el sexo del animalito
   * - **API ID Path**: cat_card.items[].sexo
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  sexo: prismic.SelectField<"hembra" | "macho">;

  /**
   * foto field in *CatCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_card.items[].foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;
}

/**
 * Default variation for CatCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CatCardSliceDefaultItem>
>;

/**
 * Slice variation for *CatCard*
 */
type CatCardSliceVariation = CatCardSliceDefault;

/**
 * CatCard Shared Slice
 *
 * - **API ID**: `cat_card`
 * - **Description**: CatCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatCardSlice = prismic.SharedSlice<
  "cat_card",
  CatCardSliceVariation
>;

/**
 * Primary content in *DogCard → Items*
 */
export interface DogCardSliceDefaultItem {
  /**
   * nombre field in *DogCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dog_card.items[].nombre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;

  /**
   * edad field in *DogCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dog_card.items[].edad
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  edad: prismic.KeyTextField;

  /**
   * lugar field in *DogCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dog_card.items[].lugar
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  lugar: prismic.KeyTextField;

  /**
   * tamanhio field in *DogCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dog_card.items[].tamanhio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tamanhio: prismic.KeyTextField;

  /**
   * esterilizacion field in *DogCard → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: dog_card.items[].esterilizacion
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  esterilizacion: prismic.BooleanField;

  /**
   * peso field in *DogCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dog_card.items[].peso
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  peso: prismic.KeyTextField;

  /**
   * vacunas field in *DogCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dog_card.items[].vacunas
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  vacunas: prismic.RichTextField;

  /**
   * descripcion field in *DogCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dog_card.items[].descripcion
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descripcion: prismic.RichTextField;

  /**
   * tipo field in *DogCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: dog
   * - **API ID Path**: dog_card.items[].tipo
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tipo: prismic.SelectField<"dog" | "cat", "filled">;

  /**
   * sexo field in *DogCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Selecciona el sexo del animalito
   * - **API ID Path**: dog_card.items[].sexo
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  sexo: prismic.SelectField<"hembra" | "macho">;

  /**
   * foto field in *DogCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dog_card.items[].foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;
}

/**
 * Default variation for DogCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DogCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<DogCardSliceDefaultItem>
>;

/**
 * Slice variation for *DogCard*
 */
type DogCardSliceVariation = DogCardSliceDefault;

/**
 * DogCard Shared Slice
 *
 * - **API ID**: `dog_card`
 * - **Description**: DogCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DogCardSlice = prismic.SharedSlice<
  "dog_card",
  DogCardSliceVariation
>;

/**
 * Primary content in *Evento → Items*
 */
export interface EventoSliceDefaultItem {
  /**
   * foto field in *Evento → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.items[].foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;

  /**
   * titulo field in *Evento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.items[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * descripcion field in *Evento → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.items[].descripcion
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descripcion: prismic.RichTextField;

  /**
   * ubicacion field in *Evento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.items[].ubicacion
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ubicacion: prismic.KeyTextField;

  /**
   * fecha field in *Evento → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.items[].fecha
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  fecha: prismic.DateField;

  /**
   * horario field in *Evento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.items[].horario
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  horario: prismic.KeyTextField;

  /**
   * contacto field in *Evento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: evento.items[].contacto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contacto: prismic.KeyTextField;
}

/**
 * Default variation for Evento Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<EventoSliceDefaultItem>
>;

/**
 * Slice variation for *Evento*
 */
type EventoSliceVariation = EventoSliceDefault;

/**
 * Evento Shared Slice
 *
 * - **API ID**: `evento`
 * - **Description**: Evento
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventoSlice = prismic.SharedSlice<"evento", EventoSliceVariation>;

/**
 * Primary content in *FotosCaso → Items*
 */
export interface FotosCasoSliceDefaultItem {
  /**
   * foto field in *FotosCaso → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fotos_caso.items[].foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;
}

/**
 * Default variation for FotosCaso Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FotosCasoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FotosCasoSliceDefaultItem>
>;

/**
 * Slice variation for *FotosCaso*
 */
type FotosCasoSliceVariation = FotosCasoSliceDefault;

/**
 * FotosCaso Shared Slice
 *
 * - **API ID**: `fotos_caso`
 * - **Description**: FotosCaso
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FotosCasoSlice = prismic.SharedSlice<
  "fotos_caso",
  FotosCasoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AdopcionesDocument,
      AdopcionesDocumentData,
      AdopcionesDocumentDataSlicesSlice,
      ContactoDocument,
      ContactoDocumentData,
      ContactoDocumentDataSlicesSlice,
      DonacionesDocument,
      DonacionesDocumentData,
      DonacionesDocumentDataSlicesSlice,
      EventosDocument,
      EventosDocumentData,
      EventosDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      IndexDocument,
      IndexDocumentData,
      IndexDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataSlicesSlice,
      NosotrosDocument,
      NosotrosDocumentData,
      NosotrosDocumentDataSlicesSlice,
      RescatistasDocument,
      RescatistasDocumentData,
      RescatistasDocumentDataSlicesSlice,
      RescatistasDocumentDataSlices2Slice,
      RescatistasDocumentDataSlices3Slice,
      RescatistasDocumentDataSlices4Slice,
      AllDocumentTypes,
      CardRescatistaSlice,
      CardRescatistaSliceDefaultPrimary,
      CardRescatistaSliceVariation,
      CardRescatistaSliceDefault,
      CasosRescateSlice,
      CasosRescateSliceDefaultItem,
      CasosRescateSliceVariation,
      CasosRescateSliceDefault,
      CatCardSlice,
      CatCardSliceDefaultItem,
      CatCardSliceVariation,
      CatCardSliceDefault,
      DogCardSlice,
      DogCardSliceDefaultItem,
      DogCardSliceVariation,
      DogCardSliceDefault,
      EventoSlice,
      EventoSliceDefaultItem,
      EventoSliceVariation,
      EventoSliceDefault,
      FotosCasoSlice,
      FotosCasoSliceDefaultItem,
      FotosCasoSliceVariation,
      FotosCasoSliceDefault,
    };
  }
}
