// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cat_card: dynamic(() => import("./CatCard")),
  dog_card: dynamic(() => import("./DogCard")),
  evento: dynamic(() => import("./Evento")),
};
